### ISSUE TITLE
Missing dependencies in the README

### ISSUE THREAD

**Issue by jknap** [joincivil/civil-events-crawler#135]
_scripts/abi_retrieval.sh_ failed twice on my machine for the following reasons:
`/bin/sh: lerna: command not found`
`/bin/sh: rimraf: command not found`

Maybe lerna and rimraf could be added as dependencies in the README, or they could be installed in the _make setup_ command?

**Comment by petersng** [comment]
We are going to store a copy of those ABI dependencies in this repository instead of having to generate them via this script as in the `joincivil/Civil` repo they are now pre-generated. At that point, this script will not be needed. Just haven't gotten around to doing so yet.  In the meantime, we can add those as dependencies into the README as you suggested.

**Comment by petersng** [comment]
After some investigation on how to streamline this, we had actually moved the civil-specific contract wrappers to our `joincivil/go-common` repo a little while back to support use across all of our Civil repos. 

In this case, we would update that repo with our abis from `joincivil/Civil` and do the contract generation in that repo for the Civil specific contracts.  Those would then be added as a part of updating the vendor deps.

Are you looking to track your own contracts, because while our original intent was to offer developers a way to track their own contract events, the project is currently skewed towards Civil contracts in support our project.  It's possible to use this to track other contracts with some work.  Our intention is to get back to that general use case, but that's where we are right now.

In any case, I'll make some updates to the README.

**Comment by petersng** [comment]
Ok, updated the documentation in this repo and in the `joincivil/go-common` repo.  I hope this helps, feel free to reach out with any other questions or assistance.
